export const TENANT_TOKENS = {
  TENANT_REPOSITORY: 'TENANT_REPOSITORY',
  ENVIRONMENT_REPOSITORY: 'ENVIRONMENT_REPOSITORY',
  SETTINGS_REPOSITORY: 'TENANT_SETTINGS_REPOSITORY',
  USER_PROVISIONING_SERVICE: 'USER_PROVISIONING_SERVICE',
  PASSWORD_HASHER: 'PASSWORD_HASHER',
} as const;
