export const IDENTITY_TOKENS = {
  USER_REPOSITORY: Symbol('USER_REPOSITORY'),
  ROLE_REPOSITORY: Symbol('ROLE_REPOSITORY'),
  PASSWORD_RESET_TOKEN_REPOSITORY: Symbol('PASSWORD_RESET_TOKEN_REPOSITORY'),
  PASSWORD_HASHER: Symbol('PASSWORD_HASHER'),
  TOKEN_SERVICE: Symbol('TOKEN_SERVICE'),
};
