export const CAMPAIGN_REPOSITORY = 'CAMPAIGN_REPOSITORY';
export const CONTACT_REPOSITORY = 'CONTACT_REPOSITORY';
export const FILE_STORAGE_PROVIDER = 'FILE_STORAGE_PROVIDER';
export const API_KEY_VALIDATION_PORT = 'API_KEY_VALIDATION_PORT';
export const CAMPAIGN_FILE_REPOSITORY = 'CAMPAIGN_FILE_REPOSITORY';
