/**
 * Tokens de inyección de dependencias (DIP).
 * Se usan como identificadores para Custom Providers en NestJS.
 */

// Repositories (Ports)
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PASSWORD_RESET_REPOSITORY = Symbol('PASSWORD_RESET_REPOSITORY');
export const TENANT_REPOSITORY = Symbol('TENANT_REPOSITORY');
export const CAMPAIGN_REPOSITORY = Symbol('CAMPAIGN_REPOSITORY');
export const CONTACT_REPOSITORY = Symbol('CONTACT_REPOSITORY');
export const CAMPAIGN_FILE_REPOSITORY = Symbol('CAMPAIGN_FILE_REPOSITORY');
export const CALL_INTERACTION_REPOSITORY = Symbol(
  'CALL_INTERACTION_REPOSITORY',
);
export const DIALING_CONFIGURATION_REPOSITORY = Symbol(
  'DIALING_CONFIGURATION_REPOSITORY',
);
export const JURISDICTION_REPOSITORY = Symbol('JURISDICTION_REPOSITORY');
export const HOLIDAY_REPOSITORY = Symbol('HOLIDAY_REPOSITORY');
export const API_KEY_REPOSITORY = Symbol('API_KEY_REPOSITORY');
export const NOTIFICATION_LOG_REPOSITORY = Symbol(
  'NOTIFICATION_LOG_REPOSITORY',
);
export const AUDIT_EVENT_REPOSITORY = Symbol('AUDIT_EVENT_REPOSITORY');

// External Services (Ports)
export const TELEPHONY_PROVIDER = Symbol('TELEPHONY_PROVIDER');
export const SPEECH_TO_TEXT_SERVICE = Symbol('SPEECH_TO_TEXT_SERVICE');
export const TEXT_TO_SPEECH_SERVICE = Symbol('TEXT_TO_SPEECH_SERVICE');
export const CONVERSATION_ENGINE = Symbol('CONVERSATION_ENGINE');
export const FILE_STORAGE_SERVICE = Symbol('FILE_STORAGE_SERVICE');
export const EMAIL_SERVICE = Symbol('EMAIL_SERVICE');
